name: Bike Sharing Workflow CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn mlflow joblib

      - name: Run Modelling
        run: |
          # 1. Bersihkan folder mlruns lama untuk menghindari konflik ID
          rm -rf /tmp/mlruns
          
          # 2. Memastikan folder Dashboard tersedia
          mkdir -p Workflow-CI/Dashboard
          
          # 3. Masuk ke folder MLProject
          cd Workflow-CI/MLProject
          
          # 4. Jalankan MLflow dengan mode lingkungan lokal
          mlflow run . --env-manager local