name: Bike Sharing Workflow CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn mlflow joblib

      - name: Run Modelling
        run: |
          # Berikan izin akses penuh ke seluruh folder proyek
          chmod -R 777 .
          
          # Masuk ke folder lokasi script
          cd Workflow-CI/MLProject
          
          # Buat folder Dashboard dan mlruns dengan izin penuh
          mkdir -p ../Dashboard
          mkdir -p mlruns
          chmod -R 777 mlruns
          
          # Jalankan modelling dengan instruksi lokasi tracking yang jelas
          export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns
          python modelling.py