name: Bike Sharing Workflow CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn mlflow joblib

      - name: Run Modelling
        run: |
          # Memberikan izin akses penuh ke folder agar tidak Permission Denied
          chmod -R 777 .
          
          # Masuk ke folder lokasi script berada
          cd Workflow-CI/MLProject
          
          # Membuat folder yang dibutuhkan secara manual
          mkdir -p ../Dashboard
          mkdir -p mlruns
          chmod -R 777 mlruns
          
          # Menjalankan modelling
          python modelling.py